apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stellaris
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/trif0lium/stellari.sh.git
    targetRevision: HEAD
    path: deployments/stellaris
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
