apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ingress-prod
spec:
  secretName: ingress-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: whoami.stl.fleeingsunlight.dev
  dnsNames:
    - whoami.stl.fleeingsunlight.dev
    - argocd.stl.fleeingsunlight.dev
