name: Build
on:
  push:
    paths:
      - "apps/**"
      - ".github/workflows/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: marceloprado/has-changed-path@v1
        id: changed-api-gateway
        with:
          paths: apps/api-gateway
      - uses: crazy-max/ghaction-docker-meta@v1
        if: steps.changed-api-gateway.outputs.changed == 'true'
        id: docker-meta
        with:
          images: trif0lium/stellari.sh/api-gateway
          tag-sha: true
      - uses: docker/build-push-action@v2
        if: steps.changed-api-gateway.outputs.changed == 'true'
        with:
          context: .
          file: ./dockerfiles/api-gateway.Dockerfile
          tags: ${{ steps.docker-meta.outputs.tags }}
          push: true
